### PR TITLE
Update vendors

### PR DESCRIPTION
**Pull request by pjedrzejewski**

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
We have to add `"doctrine/data-fixtures": "<1.2",` because of a bug introduced in the new version.

**Comment by krafas** [comment]
@pjedrzejewski @michalmarcinkowski any ideas, when tag v.0.19 for Sylius-Standard can be expected?

**Comment by michalmarcinkowski** [comment]
@krafas probably next week!

**Comment by tamasimrei** [comment]
Any ideas about why the travis build is failing? I have very similar errors in our build, maybe I could help fixing them, if you could point me to the right direction.

**Comment by tamasimrei** [comment]
I meant the element not found and the missing redirect failures.

**Comment by tamasimrei** [comment]
A small update: now I have the same exact errors in our build, what I see in
https://travis-ci.org/Sylius/Sylius-Standard/jobs/144146528

**Comment by krafas** [comment]
@michalmarcinkowski any news about this PR?

**Comment by krafas** [comment]
@pjedrzejewski, why did you close this PR?

**Comment by pamil** [comment]
@krafas I guess it is already done in some other PR.

**Comment by krafas** [comment]
@pamil, but there is no tag for the new release (v0.19.0): https://github.com/Sylius/Sylius-Standard/releases

**Pull request closed without merging**
