### PR TITLE
[Maintenance] Sylius Rector upgrade, override PayPal route

### PR DESCRIPTION
**Pull request by Rafikooo**
Refs: 
1) https://github.com/Sylius/SyliusRector/pull/25
2) https://github.com/Sylius/Sylius/pull/14902/files#diff-cf139358e8ef0b50f18638f8ff3e9cc1c2c71a900b0503445c99403fd3e0df44R40

### CODE REVIEW

**Review by jakubtobiasz — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Comment by NoResponseMate** [comment]
Thank you, @Rafikooo!

**Comment by delyriand** [comment]
@Rafikooo @NoResponseMate is it possible to create a tag?

**Comment by jakubtobiasz** [comment]
Hi @delyriand,
a new version will be released today.

**Comment by jakubtobiasz** [comment]
@delyriand https://github.com/Sylius/Sylius-Standard/releases/tag/v1.12.4 :)

**Comment by delyriand** [comment]
Thanks, @jakubtobiasz  🙏 ❤️

**Pull request merged**
