### PR TITLE
Get config.yml in sync with one from sylius/sylius

### LINKED ISSUE #169: User defined locale ignored during installation
When using `composer create-project -s beta sylius/standard` it asks for a locale, with the default being `en_US`, but if you define `en_GB` it gets ignored and installs `en_US` as default locale. Is there a way of preventing this other that going to `app/config/config.yml`, editing the local and running `bin/console sylius:install` again? It's quite annoying and frustrating.

### PR DESCRIPTION
**Pull request by ADmad**
Closes #169.

### CODE REVIEW

**Comment by lchrusciel** [comment]
@pamil I would merge a fix like this because locale will change on each machine and add this tip from Symfony to our deployment guide

**Comment by pjedrzejewski** [comment]
Will be fixed in #187.

**Comment by pjedrzejewski** [comment]
Thanks @ADmad!

**Comment by ADmad** [comment]
@pjedrzejewski Well IMHO #187 didn't exactly fix the issue but rather circumvented it :slightly_smiling_face:.

I installed 1.0.0 stable and it no longer asks preferred locale to the user during installation when you run `composer create-project` as it did in beta3. So now I have to go and manually change `config.yml` before running `php bin/console sylius:install`, which new users won't be aware of.

**Pull request closed without merging**
