### PR TITLE
Use @sylius-ui/frontend npm package

### PR DESCRIPTION
**Pull request by jakubtobiasz**
Following https://github.com/Sylius/Sylius/pull/14529 and https://github.com/Sylius/Sylius/issues/12132.

### CODE REVIEW

**Comment by vvasiloi** [comment]
Since all `dependencies` are now `devDependencies`, are there any limitations users should be aware of?

**Comment by jakubtobiasz** [comment]
Nope, the whole application is built, so none dependency is used later.

**Comment by Ferror** [comment]
I don't understand why the Sylius frontend is dev dependency

**Comment by jakubtobiasz** [comment]
@Ferror notice all gulp, webpack, and others were in dev section. None of these packages are required by runtime, as they all are only used to build the result files. All of these deps can be placed in both dependencies and devDependencies (I mean the result will be the same) so as more deps were in dev then I placed this package as dev dependency too.

**Comment by Ferror** [comment]
> @Ferror notice all gulp, webpack, and others were in dev section. None of these packages are required by runtime, as they all are only used to build the result files. All of these deps can be placed in both dependencies and devDependencies (I mean the result will be the same) so as more deps were in dev then I placed this package as dev dependency too.

Yea they were all in devDependency and then run with GULP_ENV=prod.

**Comment by jakubtobiasz** [comment]
> > @Ferror notice all gulp, webpack, and others were in dev section. None of these packages are required by runtime, as they all are only used to build the result files. All of these deps can be placed in both dependencies and devDependencies (I mean the result will be the same) so as more deps were in dev then I placed this package as dev dependency too.
> 
> Yea they were all in devDependency and then run with GULP_ENV=prod.

Now they are `yarn build:prod` what under the hood is `yarn encore production`, I don't see any difference.

**Review by coldic3 — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Review by Rafikooo — APPROVED** [review]
I'm wondering if we should open the new branch (`1.13-dev`) as [these](https://github.com/Sylius/Sylius/pull/14529) changes are targeting `Sylius 1.13`

**Comment by Rafikooo** [comment]
Thank you, Jakub! :1st_place_medal:

**Pull request merged**
