### PR TITLE
Fix #450 - Remove useless paypal migration

### LINKED ISSUE #450: [Install] Doctrine error from PaypalPlugin
**Sylius Version** : 1.8


**Error** :

In AbstractMySQLDriver.php line 57:
                                                                                                                                                                                             
    An exception occurred while executing 'CREATE TABLE sylius_paypal_plugin_pay_pal_credentials (id VARCHAR(255) NOT NULL, payment_method_id INT DEFAULT NULL, access_token VARCHAR(255) NOT NULL, creation_time DATETIME NOT NULL, expiration_time DATETIME NOT NULL, INDEX IDX_C56F54AD5AA1164F (payment_method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB':                                                                                                                                                                  
                                                                                                                                                                                             
    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'sylius_paypal_plugin_pay_pal_credentials' already exists                                                                   
                                                                                                                                                                                             

In Exception.php line 18:
                                                                                                                            
    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'sylius_paypal_plugin_pay_pal_credentials' already exists  
                                                                                                                            

In PDOConnection.php line 52:
                                                                                                                            
    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'sylius_paypal_plugin_pay_pal_credentials' already exists  
                                                                                                                            



**How to reproduce** :

```
$ composer create-project sylius/sylius-standard project
$ cd project
$ composer update
$ php bin/console sylius:install
```

### PR DESCRIPTION
**Pull request by oallain**
Remove useless Paypal migration to fix #450 .

### CODE REVIEW

**Comment by oallain** [comment]
Hello @pamil 

You have removed Travis but it's required to make PR green.
Can you remove it from checklist?

Regards

**Comment by Zales0123** [comment]
Generally 👍 but I think we should also bump a PayPalPlugin minimal version to `^1.1`... with the current `^1.0.3`  there is still a possibility to install the version that does not support DoctrineMigrations 3.0. WDYT?

**Comment by oallain** [comment]
Hello @Zales0123 

You're right, I do it.
Thanks :heart_eyes:

**Comment by oallain** [comment]
Behat checks are so random :disappointed:

**Comment by Zales0123** [comment]
Indeed :/ we should think about switching to something more reliable for JS tests.

**Review by Zales0123 — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thanks, @oallain! :1st_place_medal:

**Pull request merged**
