### PR TITLE
[DX][Database] Configure default migration folder and update to Sylius 1.8.1

### PR DESCRIPTION
**Pull request by lchrusciel**
As mentioned in https://github.com/SyliusLabs/DoctrineMigrationsExtraBundle/pull/5

### CODE REVIEW

**Comment by jacquesbh** [comment]
@lchrusciel This has to be merged asap :/. It's causing a lot of issues for new becomers I think.

**Comment by lchrusciel** [comment]
We are waiting for #436

**Comment by jacquesbh** [comment]
@lchrusciel Go go go ! 💪

**Review by Zales0123 — APPROVED** [review]

**Comment by Zales0123** [comment]
Thank you, Łukasz! :1st_place_medal:

**Pull request merged**
