### PR TITLE
Add missing migrations

### PR DESCRIPTION
**Pull request by AdamKasp**

### CODE REVIEW

**Comment by lchrusciel** [comment]
Is it still relevant?

**Comment by pocky** [comment]
@lchrusciel Hello! This migration is still relevant. Travis build failed on #413 because of this missing migration.
@AdamKasp is it possible to fix your PR (rebase and force push)? Thanks!

**Comment by lchrusciel** [comment]
Thanks, Adam! :1st_place_medal:

**Comment by pocky** [comment]
:heart:

**Pull request merged**
