### PR TITLE
Sync with Symfony Standard v3.4

### PR DESCRIPTION
**Pull request by teohhanhui**
Some notable changes:
- Switch to `config/services.yml` (see https://github.com/symfony/symfony-standard/pull/727)
- Use autowiring (as per the assumption of https://symfony.com/doc/3.4/service_container.html#service-container-services-load-example)
- Set `provider` on each firewall (see https://github.com/symfony/symfony/pull/24378)
- Remove `trusted_proxies` from `config.yml` (see https://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3 and https://github.com/symfony/symfony-standard/pull/1060)
- Use single quotes in YAML (see https://github.com/symfony/symfony-docs/issues/5935 and https://github.com/symfony/symfony-standard/pull/1065)
- Use `%kernel.project_dir%` instead of `%kernel.root_dir%` (see https://github.com/symfony/symfony-standard/pull/1065)
- Add some missing `declare(strict_types=1);`
- Remove author blocks (same as Sylius)

### CODE REVIEW

**Comment by teohhanhui** [comment]
@pamil Any feedback on this?

**Comment by pamil** [comment]
I'm on it! :)

**Comment by pamil** [comment]
Btw. can you rebase it to `1.1` branch (it already requires Symfony 3.4)?

**Comment by teohhanhui** [comment]
Rebased.

**Comment by pamil** [comment]
The only thing that might cause issues here is "Remove bin-dir in composer.json", mostly with documentation, this PR will be good to merge after it's extracted to `master` (1.2) branch. Thanks for the effort and patience 🎉

**Comment by teohhanhui** [comment]
Reverted the changes related to removing `bin-dir`.

Added some more changes to fix some deprecation messages:
- Set `provider` on each firewall (see https://github.com/symfony/symfony/pull/24378)
- Remove `trusted_proxies` from `config.yml` (see https://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3 and https://github.com/symfony/symfony-standard/pull/1060)

**Comment by pamil** [comment]
Thanks Teoh! 🎉

**Pull request merged**
