### PR TITLE
Remove composer --no-sugest deprecated call

### PR DESCRIPTION
**Pull request by dominikhajduk**
Removed call do deprecated Composer 2 option which has no effect and will be removed in Composer 3 to prevent:

```
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
```
It's popup when building project or starting container.

Reference: https://php.watch/articles/composer-2#no--no-suggest

### CODE REVIEW

**Review by pamil — APPROVED** [review]

**Review by tarnawski — APPROVED** [review]

**Comment by dominikhajduk** [comment]
@Zales0123 @lchrusciel @GSadee can I do something more to merge that one?

**Comment by vasilvestre** [comment]
Master do not have this --no-suggest anymore, you may close this PR

**Comment by lchrusciel** [comment]
Hey Dominik,

I'm sorry for the long feedback loop. Thanks a lot for your contribution, however, this change is already applied on master.

**Comment by dominikhajduk** [comment]
Hey @lchrusciel thanks for answer. Shouldn't it be applied also to lower versions: https://docs.sylius.com/en/latest/book/contributing/code/patches.html#choose-the-right-base-branch? Or it's only for bugs?

**Pull request closed without merging**
