### PR TITLE
Upgrade Dockerfile to PHP 7.4 and sync with API Platform's setup

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by 4c0n** [comment]
It's sad that this PR is still open and did not receive any useful feedback or comments. :disappointed:

**Comment by vasilvestre** [comment]
master has been updated, the healthcheck would be nice tho, could you rebase @dunglas please ? :)

**Comment by lchrusciel** [comment]
I may bump this PR. @dunglas would you find some time to update this PR? Would be nice to finally have it merged

**Comment by Ferror** [comment]
Well, it's been more than 2 years, and docker and Sylius changed. In my opinion, there is no chance this PR will be merged ever :(

**Pull request closed without merging**
