### PR TITLE
[WIP] Replace Gulp with Webpack Encore

### PR DESCRIPTION
**Pull request by kulczy**
The basic commands stay the same:
`yarn` - install node modules
`yarn build` - create a production build

There are also new commands:
`yarn dev` - compile assets once
`yarn watch` - compile assets automatically when files change
`yarn server` - start developer server, compile assets and refresh browser automatically when files change

You can add additional `:shop` or `:admin` to each command to compile assets from the selected bundle (e.g. `yarn dev:shop`)

Admin and Shop have their entry files (`./assets/admin/main.js`, `./assets/shop/main.js`). 
If you want to add new asset (js, css or image file), you must import it in one of the entry files.

If you want to insert a new image in the twig file, you should now pass the second parameter in the asset function, corresponding to the selected entry file (e.g.`{{ asset('assets/shop/images/logo.png', 'shop') }}`)

### CODE REVIEW

**Comment by loevgaard** [comment]
What's the status with this one, @kulczy :D

**Comment by michael-roth** [comment]
I followed the guide in the Sylius docs for [using Encore](https://docs.sylius.com/en/latest/theming/webpack.html) and had to add an import to the slick-carousel css into my entry.js to make the carousel on demo homepage work.

I think this import might be missing in src\Sylius\Bundle\ShopBundle\Resources\private\entry.js (or app.js)?

**Comment by floriangosse** [comment]
I there something the community can help with to get this feature done?

**Comment by floriangosse** [comment]
Is there no longer a plan to migrate from Gulp to Webpack (Encore)?

**Comment by Kocal** [comment]
@floriangosse see #375

**Pull request closed without merging**
