### PR TITLE
Fix container build missing composer.lock

### PR DESCRIPTION
**Pull request by Dragnucs**
Do not copy non existent composer.lock. The image build correctly without this file anyways.

Related issues: #596, #606, #614.

### CODE REVIEW

**Comment by coldic3** [comment]
Hi, I faced up the same problem. I'm not sure we should get rid of this part. The main idea behind copying `composer.lock` is to guarantee consistent package versions. Without it, every single build will cause a potentially unintended silent composer update. Silent because the lock file won't change but the vendor will and it will be very confusing and hard to detect in real projects.

Look at the [Dockerfile in API Platform template](https://github.com/api-platform/api-platform/blob/ac68010c818bde422b97a7044b8df04176e970a4/api/Dockerfile#L84) where's the same `COPY` but the difference is that `composer.lock` is in the repository.

Another way I see is to copy `composer.lock` only if the file exists. Unfortunately, it is possible only by some workarounds like using wildcards. Wildcard character set expression seems to me to be the safest option. What do you think to just replace `composer.lock` with `compose[r].lock` or something like that? It solves our problem without any side effects probably.

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Hey @Dragnucs, thanks a lot for proposal. 

Kevin, thanks for checking it up and making research. Keeping composer.lock is no go for us right now, as we are supporting different stacks and it would require different locks for different versions. We may consider providing lock file for docker only if it can be do effort-free during release. Can you confirm, that this fix the main issue?

**Comment by lchrusciel** [comment]
Oh, this is already fixed on master branch. Can you check it?

**Comment by vasilvestre** [comment]
On master, COPY instruction now use "composer.*" instead of "composer.json composer.lock". I've tried to build master minutes ago and it went just fine.

**Comment by coldic3** [comment]
Yeah, the solution with `composer.*` fixes the main issue :) However, it's worth mentioning it copies all the files starting with "composer." so it's good only as far as `composer.json` and `composer.lock` are the only files with "composer." prefix in the root directory.

**Comment by Zales0123** [comment]
Already fixed in https://github.com/Sylius/Sylius-Standard/pull/625, thank you, everyone, for the discussion and your contribution! 🎉 🚀

**Comment by eradionov** [comment]
Was it really fixed?
Still occurs for me

**Pull request closed without merging**
