### PR TITLE
Upgrade to latest sylius + deps + fos rest bundle

### PR DESCRIPTION
**Pull request by bendavies**
Upgrades Sylius standard for https://github.com/Sylius/Sylius/pull/7349

### CODE REVIEW

**Comment by lchrusciel** [comment]
The build is failing because of missing migration from main sylius repository. We could copy and paste them from the main repository, but there is also another solution(which I found easier to maintain).
We can create a file, lets say `app/config/sylius_migration.yml`
```yml
# app/config/sylius_migration.yml

name: Sylius Migrations
migrations_namespace: Sylius\Migrations
table_name: sylius_migrations
migrations_directory: "vendor/sylius/sylius/app/migrations/"
```

and than, just run migration from this file:
```bash
$ sf d:m:m --configuration app/config/sylius_migration.yml
```
[Here](http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/introduction.html#configuration) are some docs about it. 
What would you say?

**Comment by bendavies** [comment]
@lchrusciel doesn't seem great. a user needs to implement their own migrations so would need more than 1 directory for migrations?

**Comment by lchrusciel** [comment]
@bendavies No. the main migration folder stay the same. It just allow us, to run migration from Sylius vendor if you need. Normally, it is not taken into account. We just should put this config the content to separate file and make it easier for others to run Sylius migration without required copy-pasting.

**Comment by bendavies** [comment]
@lchrusciel got ya!

**Comment by bendavies** [comment]
@lchrusciel have you guys decided how you want to proceed?

**Comment by lchrusciel** [comment]
It is not up to me. /cc @pjedrzejewski @michalmarcinkowski Should we copy & paste migration from main Sylius repository, or allow to use them without duplication?

**Comment by michalmarcinkowski** [comment]
IMO the solution proposed by @lchrusciel is fine. @pjedrzejewski?

**Comment by bendavies** [comment]
what about the existing single migration in `app/migrations` and the `doctrine_migrations` config in `config.yml`?

**Comment by bendavies** [comment]
@lchrusciel i pushed a commit. same idea as yours

**Comment by lchrusciel** [comment]
It is working, so good enough for me. But the question is, shouldn't we provide a way to easily run Sylius migration from Sylius-Standard... Anyway, it can be a topic for RFC

**Comment by bendavies** [comment]
Yeah, i'm unsure what to do with the current `app/migrations` directory. copy the sylius ones in or remove the one that is there?

**Comment by michalmarcinkowski** [comment]
How about removing the migrations from Sylius-Standard and just create a schema on travis for tests? The migrations are already tested on Sylius/Sylius repository, so there is no benefit of running them here as well.

**Comment by liverbool** [comment]
Consider to use `zone` in sylius config.
http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#zone-listener

**Comment by pjedrzejewski** [comment]
Thanks Ben!

**Pull request merged**
