### PR TITLE
Let's use symfony/runtime

### PR DESCRIPTION
**Pull request by Ferror**
I would like to propose using symfony/runtime component that has multiple advantages.

1. Simplifies the console and index entry points
2. Enables the ability to use other runtimes... Like Swoole, Roadrunner etc. https://github.com/php-runtime

https://symfony.com/blog/new-in-symfony-5-3-runtime-component

### CODE REVIEW

**Review by loic425 — APPROVED** [review]

**Review by coldic3 — APPROVED** [review]

**Review by NoResponseMate — APPROVED** [review]

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Can we migrate https://github.com/Sylius/Sylius as well? Plus, publish some blogpost with recommendations to upgrade?

**Comment by lecajer** [comment]
Hi, how do you install Symfony Runtime in an existing project ?

I keep getting this error: 
>Fatal error: Uncaught LogicException: Symfony Runtime is missing. Try running "composer require symfony/runtime"

I tryed with :
>docker-compose up --build -V --force-recreate php

**Comment by lchrusciel** [comment]
Hey Jeremie! You have to adjust a few things inside of your project:
1. require runtime on your project 
image
2. adjust `public/index.php` and `bin/console` as done here

@Ferror perhaps we should publish this somewhere on Sylius blog

**Comment by lecajer** [comment]
Thanks @lchrusciel . I thought it was better to let the `composer install` in the Dockerfile do it.

**Pull request merged**
