### PR TITLE
Remove usage of libsass

### PR DESCRIPTION
**Pull request by Nek-**
Follow up https://github.com/Sylius/Sylius/pull/13488

### CODE REVIEW

**Review by GSadee — APPROVED** [review]

**Comment by Zales0123** [comment]
Hello @Nek-! I've rebased your PR but it still has some bugs, can you please fix them? I would love to merge it :) 🖖

**Comment by Nek-** [comment]
@Zales0123 thanks for your concern, but issues are related to the comment I posted here: https://github.com/Sylius/Sylius/pull/13488#issuecomment-1086160733 that remain unanswered atm.

**Comment by Ferror** [comment]
@Nek- Yea, but the issue pipelines are failing is because usage of gulp-sass in Sylius/Sylius ex. https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js I will try to help you with that as it may create multiple issues 😄 

But I'm really happy you decided to help us as I'm currently struggling with Docker and legacy node requirements.

What needs to be done is `Each Sylius/Sylius Bundle's gulp file has to be upgraded to the latest sass.`

PS. Don't mind to contact me on Slack ❤️

**Comment by Nek-** [comment]
@Ferror it's already done. cf link I just posted. The point is that it's not released in a stable release yet.

**Comment by Ferror** [comment]
> @Ferror it's already done. cf link I just posted. The point is that it's not released in a stable release yet.

What do you mean by "CF" and where did you post it? 😄

**Comment by Nek-** [comment]
sorry cf is french for _see_ x).

https://github.com/Sylius/Sylius/pull/13488#issuecomment-1086160733

**Pull request closed without merging**
