### PR TITLE
[Maintenance] PHP Attributes in the Entity classes

### PR DESCRIPTION
**Pull request by Rafikooo**
The follow-up to: https://github.com/Sylius/Sylius-Standard/pull/865 & https://github.com/Sylius/Sylius-Standard/pull/881

Since we do not use PHP 7.4 anymore, it's preferable <s>to move into PHP Attributes</s> to support both annotations and attributes with default annotations setting 🎉

### CODE REVIEW

**Review by NoResponseMate — APPROVED** [review]
You can also add it as the default type in [doctrine's config](https://github.com/Sylius/Sylius-Standard/blob/1.12/config/packages/doctrine.yaml).
If someone prefers to still use annotations, they can easily change it.

**Comment by Rafikooo** [comment]
@NoResponseMate, as I recall, we agreed that in Sylius 1.12 we will stick with annotations, giving the ability to switch to the attributes, but we will use attributes as the default configuration with Sylius 1.13

**Review by jakubtobiasz — APPROVED** [review]
I don't understand why we provide it that way, when there's a Rector rule https://getrector.org/blog/how-to-upgrade-annotations-to-attributes (Rector is installed by default since 1.12 AFAIR).

If we really need it to have declared, I'm fine with that 👌🏼.

**Comment by jakubtobiasz** [comment]
Thanks, Rafał! :tada:

**Pull request merged**
