### PR TITLE
typo in security.yml

### PR DESCRIPTION
**Pull request by markpol**
the same one as in the Sylius upstream package: https://github.com/Sylius/Sylius/pull/5975

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
@markpol Could you have a look at the failing build? Thanks!

**Comment by michalmarcinkowski** [comment]
This can be fixed only if we update `sylius/sylius`.

**Comment by kralos** [comment]
@markpol you just need to `composer update` again on your branch to yank the new `sylius/sylius` version and then commit your new `composer.lock`

**Comment by michalmarcinkowski** [comment]
Fixed in #130.

**Pull request closed without merging**
