### PR TITLE
[ErrorHandler][FOSRestBundle] Unable to find template "" (looked into: ...)

### PR DESCRIPTION
**Pull request by Prometee**
See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1853 for explanations.

### CODE REVIEW

**Comment by igormukhingmailcom** [comment]
@lchrusciel, this bugfix is very useful. I had tons of `Unable to find template "" (looked into: ...)` exceptions last month or so and looks like this PR fixing it (I haven't tested by myself, but it should I guess).

Also, I believe `zone`s should be added to ShopApiPlugin to https://github.com/Sylius/ShopApiPlugin/blob/master/tests/Application/config/packages/fos_rest.yaml and `README.md`

Related hints: https://gist.github.com/igormukhingmailcom/3196a8cdf87a5c2ac18bac8287034880#3-unable-to-find-template--looked-into-

**Comment by lchrusciel** [comment]
We need a green build to have it merged

**Comment by Prometee** [comment]
@lchrusciel get it ;), I fx it today if I found enough time don't worry !

**Comment by Prometee** [comment]
@igormukhingmailcom I agree, I also add it for my own project with ShopApiPlugin enable.

**Comment by lchrusciel** [comment]
We need #394 to wait for

**Comment by igormukhingmailcom** [comment]
Also, it would be nice if this PR title will be changed to something like `Unable to find template "" (looked into: ...)` - that way it can be googled more easier I believe

**Comment by lchrusciel** [comment]
Hey Francis, could you rebase this PR?

**Comment by Prometee** [comment]
Hy @lchrusciel ! To the master branch or another branch ?

**Comment by lchrusciel** [comment]
unfortunately, build is still failing :( Can you investigate it why?

**Comment by Prometee** [comment]
The `master` branch is broken and I have problem switching to the `1.7` branch.

**Comment by pamil** [comment]
The base of this pull-request was changed, you need fetch and reset your local branch 
if you want to add new commits to this pull request. **Reset before you pull, else commits
may become messed-up.**

Unless you added new commits (to this branch) locally that you did not push yet, 
execute `git fetch origin && git reset "patch-2"` to update your local branch.
 
Feel free to ask for assistance when you get stuck :+1:

**Comment by lchrusciel** [comment]
There is a possibility, that error occurs due to high amount of versions to resolve. I hope switch to composer v2 will solve this issue partially. Let's see after #434 merge

**Comment by clem21** [comment]
Hi Francis,
I checkout your PR and rebase here #448 yours is going to be closed

**Comment by Prometee** [comment]
@clem21 Thank you but it's kind of useless and make a duplicate.

@lchrusciel as the master branch has a failed build, this PR cannot be green.

**Comment by lchrusciel** [comment]
Hey @Prometee, I've asked @clem21 for some help here. Let's see if we can fix the main build and finally make this PR land in the core ;)

**Comment by Zales0123** [comment]
I think it can be closed, thank you 🖖

**Pull request closed without merging**
