### PR TITLE
Add missing migration for taxon

### PR DESCRIPTION
**Pull request by pocky**
Fix another missing migration on sylius_taxon :)

### CODE REVIEW

**Comment by pocky** [comment]
@lchrusciel And it works well! (except for migration :heart:)

**Comment by lchrusciel** [comment]
Can you check the migration file and fix potential CS issues? The build is red :(

**Comment by pocky** [comment]
Oh sorry :x I will fix these errors tonight :)

**Comment by lchrusciel** [comment]
Don't worry ;)

**Comment by lchrusciel** [comment]
Fixed already in #410. Nonetheless, thanks a lot for your contribution.

**Pull request closed without merging**
